# Generated by Django 4.1.3 on 2022-12-28 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_date_posted_post_pub_date_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
