# Generated by Django 4.1.3 on 2023-01-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_username_post_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fullname',
            field=models.CharField(max_length=25),
        ),
    ]
