# Generated by Django 4.1.3 on 2023-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_fullname_post_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
