# Generated by Django 4.1.3 on 2023-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(height_field=50, max_length=50, upload_to='images', width_field=70),
        ),
    ]
